apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    operator:
      replicas: 1
    cni:
      confPath: /var/lib/cni/net.d

---

apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.6.2
  targetNamespace: longhorn-system
  valuesContent: |-
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    persistence:
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
    #defaultSettings:
    #  defaultDataPath: /data/longhorn

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  repo: https://bitnami-labs.github.io/sealed-secrets
  chart: sealed-secrets
  version: 2.16.1
  targetNamespace: kube-system
  valuesContent: |-
    fullnameOverride: sealed-secrets-controller
    #image:
    #  tag: v0.19.3

---

apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 7.3.8
  targetNamespace: argocd
  valuesContent: |-
    configs:
      cm:
        ui.bannercontent: "SP-CC-VM"
        ui.bannerurl: ""
        ui.bannerpermanent: "true"
        ui.bannerposition: "both"
    notifications:
      enabled: false
    dex:
      enabled: false

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd-image-updater
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argocd-image-updater
  version: 0.11.0
  targetNamespace: argocd
  valuesContent: |-
    config:
      registries:
      - name: GitHub Container Registry
        prefix: ghcr.io
        api_url: https://ghcr.io
        ping: no
        credentials: pullsecret:argocd/argocd-image-updater-ghcr-secret
        insecure: true

---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.15.1
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true

---

apiVersion: v1
kind: Namespace
metadata:
  name: logs

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
