name: Build SuperProtocol OS image
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      debug:
        required: false
        type: string
        default: false
      push-to-registry:
        required: false
        type: string
        default: no
      target-branch:
        required: false
        type: string
        default: ""

jobs:
  build-asset:
    runs-on: arc-self-hosted

    steps:
      - name: Login to Kata Containers quay.io
        if: ${{ inputs.push-to-registry == 'yes' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0 # This is needed in order to keep the commit ids history

      - name: Build
        run: |
          sp-build.sh
          build_dir=$(readlink -f build)
          ls -la $build_dir
          rm -rf $build_dir/rootfs
        env:
          PUSH_TO_REGISTRY: ${{ inputs.push-to-registry }}
          ARTEFACT_REGISTRY: ghcr.io
          ARTEFACT_REGISTRY_USERNAME: ${{ github.actor }}
          ARTEFACT_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: ${{ inputs.target-branch }}
          RELEASE: ${{ inputs.stage == 'release' && 'yes' || 'no' }}
          DEBUG: ${{ inputs.debug }}

      - name: store-artifacts
        uses: actions/upload-artifact@v4
        with:
          #name: super-amd64${{ inputs.tarball-suffix }}
          path: build/**
          retention-days: 1
          if-no-files-found: error
